name: Check Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Install solc-select
        run: |
          python3 -m venv solgoenv
          source solgoenv/bin/activate
          pip3 install solc-select
          pip3 install slither-analyzer

      - name: Setup solc
        run: |
          source solgoenv/bin/activate
          solc-select install 0.8.19
          solc-select use 0.8.19

      - name: Run Tests
        run: |
          source solgoenv/bin/activate
          solc-select install 0.8.19
          solc-select use 0.8.19 
          make test